Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto02/DesenvolvimentoWeb.Projeto02/Controllers/EventosController.cs
using DesenvolvimentoWeb.Projeto02.Dados;
using DesenvolvimentoWeb.Projeto02.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DesenvolvimentoWeb.Projeto02.Controllers
{
    public class EventosController : Controller
    {
        private EventosDaoImpl _eventosDaoImpl {get;set;}

        //EventosContext é passado por Injecao de Dependencia
        public EventosController(EventosContext ctx)
        {
            _eventosDaoImpl = new EventosDaoImpl(ctx);
        }

        public IActionResult Index()
        {
            return View();
        }

        //Inclusão do Evento
        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult IncluirEvento()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IncluirEvento(Evento evento, IFormFile Foto)
        {
            if (Foto != null)
            {
                evento.MimeType = Foto.ContentType;
                evento.Foto = Foto.ToByteArray();
            }

            _eventosDaoImpl.ProcessarDB(evento, TipoOperacaoBd.Added);
            return RedirectToAction("ListarEventos");
        }

        //Buscando a Imagem
        public FileResult BuscarFoto(int id)
        {
            var evento = _eventosDaoImpl.BuscarPorId(id);
            return File(evento.Foto, evento.MimeType);
        }

        //Listando Eventos
        public IActionResult ListarEventos()
        {
            var lista = _eventosDaoImpl.Listar();
            return View(lista);
        }

        //Alterando Eventos
        [HttpGet]
        public IActionResult AlterarEvento(int id)
        {
            return ExecutarEvento(id, "AlterarEvento");
        }
        [HttpPost]
        public IActionResult AlterarEvento(Evento evento, IFormFile Foto)
        {
            if (Foto != null)
            {
                evento.MimeType = Foto.ContentType;
                evento.Foto = Foto.ToByteArray();
            }

            _eventosDaoImpl.ProcessarDB(evento, TipoOperacaoBd.Modified);

            return RedirectToAction("ListarEventos");
        }

        //Ver os Detalhes
        public IActionResult VerDetalhes(int id)
        {
            return ExecutarEvento(id, "VerDetalhes");
        }

        //Remover Evento
        [HttpGet]
        public IActionResult RemoverEvento(int id)
        {
            return ExecutarEvento(id, "RemoverEvento");
        }
        [HttpPost]
        public IActionResult RemoverEvento(Evento evento)
        {
            _eventosDaoImpl.ProcessarDB(evento, TipoOperacaoBd.Deleted);

            return RedirectToAction("ListarEventos");
        }

        //Action HTTPGet Comum (Compartilhado)
        [HttpGet]
        private IActionResult ExecutarEvento(int id, string viewName)
        {
            var evento = _eventosDaoImpl.BuscarPorId(id);
            if (evento == null)
            {
                @ViewData["MensagemErro"] = "Nenhum evento encontrado";
                return View("_Erro");
            }
            return View(viewName, evento);
        }

    }
}

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto02/DesenvolvimentoWeb.Projeto02/Controllers/ParticipantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DesenvolvimentoWeb.Projeto02.Dados;
using DesenvolvimentoWeb.Projeto02.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DesenvolvimentoWeb.Projeto02.Controllers
{
    public class ParticipantesController : Controller
    {
        private EventosDaoImpl _eventosDaoImpl { get; set; }
        private ParticipantesDaoImpl _participanteDaoImpl { get; set; }

        public ParticipantesController(EventosContext ctx)
        {
            _eventosDaoImpl = new EventosDaoImpl(ctx);
            _participanteDaoImpl = new ParticipantesDaoImpl(ctx);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult IncluirParticipante()
        {
            ViewBag.ListaDeEventos = new SelectList(_eventosDaoImpl.Listar(), "Id", "Descricao");
            return View();
        }

        [HttpPost]
        public IActionResult IncluirParticipante(Participante participante)
        {
            if(participante.IdEvento == 0)
                ModelState.AddModelError("IdEvento", "Informe um evento");

            if (participante.Cpf != null)
            {
                if (!participante.Cpf.ValidarCPF())
                    ModelState.AddModelError("Cpf", "Cpf inválido");
            }
            else
            {
                ModelState.AddModelError("Cpf", "Informe um CPF");
            }

            if (!ModelState.IsValid)
                return IncluirParticipante();

            _participanteDaoImpl.ProcessarDB(participante, TipoOperacaoBd.Added);

            return RedirectToAction("Index");
        }

        public IActionResult ListarParticipantesAjax(int idEvento)
        {
            ViewBag.ListaDeEventos = new SelectList(_eventosDaoImpl.Listar(), "Id", "Descricao");
            if(idEvento == 0)
            {
                return View();
            }
            else
            {
                var listaDeEventos = _participanteDaoImpl.ListarPorEvento(idEvento);
                return PartialView("_ListarParticipantes", listaDeEventos);
            }
        }
    }
}

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto02/DesenvolvimentoWeb.Projeto02/Views/Shared/_Erro.cshtml
@{
    ViewData["Title"] = "Erro";
}

<h2 class="text-danger">Ops! Ocorreu o seguinte erro:</h2>
<div class="alert alert-danger">
    @ViewData["MensagemErro"]
</div>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto02/DesenvolvimentoWeb.Projeto02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesenvolvimentoWeb.Projeto02</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Eventos" asp-action="Index" class="navbar-brand">Eventos</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Eventos" asp-action="Index">Gestão de Eventos</a></li>
                    <li><a asp-area="" asp-controller="Participantes" asp-action="Index">Gestão de Participantes</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ASPNET Core</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto02/DesenvolvimentoWeb.Projeto02/Views/Shared/_ListarParticipantes.cshtml
@model IEnumerable<DesenvolvimentoWeb.Projeto02.Models.Participante>

<table class="table table-bordered table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataNascimento)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>