Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DesenvolvimentoWeb.Projeto01.Models
{
    public class Produto
    {
        public int? Codigo { get; set; }
        public string Descricao { get; set; }
        public double Preco { get; set; }
        [Display(Name = "Data de Cadastro")]
        public DateTime DataCadastro { get; set; }
    }
}

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DesenvolvimentoWeb.Projeto01.Models;

namespace DesenvolvimentoWeb.Projeto01.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        
    }
}

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DesenvolvimentoWeb.Projeto01.Models;

namespace DesenvolvimentoWeb.Projeto01.Controllers
{
    public class InicioController : Controller
    {
        //primeiro action: string
        public string MostrarTexto()
        {
            return $"<h1>Conceitos do MVC</h1>";
        }

        public FileResult MostrarPDF()
        {
            return File("arquivos/apostila.pdf", "application/pdf");
        }

        public FileResult MostrarImagem()
        {
            return File("arquivos/leao.jpg", "image/jpeg");
        }

        public ActionResult MostrarConteudo()
        {
            return View("Index");
        }

        public IActionResult Index()
        {
            return View();
        }

        //trabalhando com a classe produto
        //1 - Criando um objeto e aprensentado para o usuario
        public IActionResult MostrarProduto()
        {
            var produto = new Produto { Codigo = 1, Descricao = "Produto 01", Preco = 25.36 };

            return View(produto);
        }

        //2 - Lista de Produtos - List
        public IActionResult ListarProdutos1()
        {
            List<Produto> lista = new List<Produto> {
                new Produto{ Codigo = 1, Descricao = "Produto 01", Preco = 63.16},
                new Produto{ Codigo = 2, Descricao = "Produto 02", Preco = 40.99},
                new Produto{ Codigo = 3, Descricao = "Produto 03", Preco = 17.97},
                new Produto{ Codigo = 4, Descricao = "Produto 04", Preco = 52.14},
                new Produto{ Codigo = 5, Descricao = "Produto 05", Preco = 98.99}
            };

            return View(lista);
        }

        //3 - Lista de Produtos - HashSet
        public IActionResult ListarProdutos2()
        {
            HashSet<Produto> lista = new HashSet<Produto> {
                new Produto{ Codigo = 1, Descricao = "Produto 06", Preco = 13.16},
                new Produto{ Codigo = 2, Descricao = "Produto 07", Preco = 32.99},
                new Produto{ Codigo = 3, Descricao = "Produto 08", Preco = 25.97}
            };

            return View("ListarProdutos1", lista);
        }

        //4 - Formulario de cadastro de produtos
        [HttpGet]
        public IActionResult CadastroProduto()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CadastroProduto(Produto prod)
        {
            if(prod.Codigo <= 100)
            {
                ModelState.AddModelError("Codigo", "O código deve ser maior que 100");
            }

            if (!ModelState.IsValid)
            {
                return View();
            }
            return View("MostrarProduto", prod);
        }
    }
}

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Inicio/CadastroProduto.cshtml
@model Produto
@{
    ViewData["Title"] = "CadastroProduto";
}

<h2>Formulário - Cadastro de Produtos</h2>

<form asp-action="CadastroProduto">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="Codigo"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo"></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="Descricao"></label>
                <input asp-for="Descricao" class="form-control" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="Preco"></label>
                <input asp-for="Preco" class="form-control" />
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="DataCadastro"></label>
                <input asp-for="DataCadastro" class="form-control" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <input type="submit" value="Enviar" />
        </div>
    </div>
</form>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Inicio/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Selecione uma opção</h2>

<ul class="list-group">
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="MostrarPDF">Mostrar PDF</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="MostrarImagem">Mostrar Imagem</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="MostrarConteudo">Mostrar Conteúdo</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="MostrarProduto">Mostrar Produto</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="ListarProdutos1">Listrar Produto (List)</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="ListarProdutos2">Listrar Produto (HashSet)</a></li>
    <li class="list-group-item"><a asp-controller="Inicio" asp-action="CadastroProduto">Cadastro Produto</a></li>
    
</ul>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Inicio/ListarProdutos1.cshtml
@model IEnumerable<Produto>
@{
    ViewData["Title"] = "ListarProdutos1";
}

<h2>Lista de Produtos</h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Codigo</td>
                <td>@item.Descricao</td>
                <td>@item.Preco.ToString("c")</td>
            </tr>
        }

    </tbody>
</table>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Inicio/MostrarProduto.cshtml
@model Produto
@{
    ViewData["Title"] = "MostrarProduto";
}

<h2>Cadastro de Produtos</h2>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Código</th>
            <th>Descrição</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Codigo</td>
            <td>@Model.Descricao</td>
            <td>@Model.Preco.ToString("c")</td>
        </tr>
    </tbody>
</table>

Rogerio_AspNetCore_20191211/Projeto03/DesenvolvimentoWeb.Projeto01/DesenvolvimentoWeb.Projeto01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesenvolvimentoWeb.Projeto01</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DesenvolvimentoWeb.Projeto01</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Inicio" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - DesenvolvimentoWeb.Projeto01</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>